# 𝓒𝓸𝓭𝓮𝓭 𝓫𝔂 𝓔𝔁𝓸𝓼𝓶𝓲𝓾𝓶 (vk.com/prodbyhakin)
# Спасибо, что используете мой плагин!

Particles:

  # Начальная точка
  start-point:
    world: "world"
    x: 0
    y: 112
    z: 0

  # Тип, можно найти на: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
  type: SMOKE_LARGE

  # Количество
  count: 5000

  # Разброс по XYZ
  offset:
    x: 250
    y: 250
    z: 250

  # Как часто они будут появляться (в тиках)
  delay: 2
